# Generated by Django 4.1.2 on 2022-11-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_application_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date']},
        ),
    ]
