# Generated by Django 4.1.2 on 2022-11-14 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_application_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='files/<function get_name_file at 0x000002C276502830>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
    ]
