# Generated by Django 4.1.2 on 2022-11-14 12:48

import django.core.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, help_text='Максимальный размер изображения 2MB', null=True, upload_to='images/<function get_name_file at 0x0000025CE4B52560>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp']), web.models.limited_image], verbose_name='Картинка'),
        ),
    ]
