# Generated by Django 4.1.2 on 2022-11-16 13:35

import django.core.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_application_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, help_text='Максимальный размер изображения 2MB', max_length=254, null=True, upload_to=web.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp']), web.models.limited_image], verbose_name='Картинка'),
        ),
    ]
